### ISSUE TITLE
Appointment time is not showing the full schedule on the calendar

### ISSUE THREAD

**Issue by powolnymarcel** [LaravelDaily/LaraAppointments-QuickAdminPanel#1]
Hello,
On the "appointment" page,  time is not showing the full schedule on the calendar

Example: I set an appointment from 11am to 4pm and I only see on the calendar that the event is showing from 11am to 12pm.

Any idea why ?

btw, awesome work ;)

**Comment by LaravelDaily** [comment]
@powolnymarcel thanks for noticing this bug! Fixed it here: https://github.com/LaravelDaily/LaraAppointments-QuickAdminPanel/commit/eafae8698ba6bb490d867bc3a58ac7ac90bee2ce

If you don't provide finish time, by default FullCalendar will show it as 2 hours.
